import { DEFAULT_DECIMALS } from '../constants/misc'

export default (value: number, decimals?: number): string =>
  value !== undefined
    ? Intl.NumberFormat('en', {
        maximumFractionDigits: decimals ? decimals : DEFAULT_DECIMALS,
      }).format(value)
    : ''

/**
 * Removes comma from string. ex: 1,700.25 = 1700.25
 * Returns a parsed number in float notation
 */
export const stringToValidFloat = (strAmount: string): number => {
  const validFloat = strAmount.replace(',', '') || '0'
  return parseFloat(validFloat)
}

export const fixedNumber = (amount: number, decimalsRound: number) => {
  const decimalsPow = Math.pow(10, decimalsRound) // For n decimals, multiply and divide by 10^n
  const roundedAmount = amount + Number.EPSILON // to evade rounding issues generated by toFixed method
  const result = Math.round(roundedAmount * decimalsPow) / decimalsPow
  return result
}
